fragment DefaultAffectedByIssueInfo on AffectedByIssue {
    id
    ... on Named {
        name
        description
    }
    ... on ComponentVersion {
        version
        component {
            name
            description
        }
    }
    ... on InterfaceSpecificationVersion {
        version
        interfaceSpecification {
            name
            description
        }
    }
    ... on Interface {
        interfaceDefinition {
            interfaceSpecificationVersion {
                version
                interfaceSpecification {
                    name
                    description
                }
            }
        }
    }
    __typename
}

fragment DetailedAffectedByIssueInfo on AffectedByIssue {
    ...DefaultAffectedByIssueInfo
    ... on Component {
        versions(first: $sublistCount) {
            nodes {
                id
                version
            }
        }
    }
    ... on InterfaceSpecification {
        versions(first: $sublistCount) {
            nodes {
                id
                version
                interfaceDefinitions(
                    first: $sublistCount
                    filter: { visibleInterface: {}, componentVersion: { component: { id: { eq: $trackable } } } }
                ) {
                    nodes {
                        visibleInterface {
                            id
                        }
                    }
                }
            }
        }
    }
    ... on InterfaceSpecificationVersion {
        interfaceDefinitions(
            first: $sublistCount
            filter: { visibleInterface: {}, componentVersion: { component: { id: { eq: $trackable } } } }
        ) {
            nodes {
                visibleInterface {
                    id
                }
            }
        }
    }
}