fragment DefaultIssueTemplateInfo on IssueTemplate {
    id
    name
    description
    templateFieldSpecifications {
        name
        value
    }
}

fragment IssueTemplateFields on IssueTemplate {
    id
    name
    description
    extends {
        nodes {
            id
        }
    }
    issueTypes {
        nodes {
            name
            description
            iconPath
        }
    }
    issuePriorities {
        nodes {
            name
            description
            value
            iconPath
        }
    }
    issueStates {
        nodes {
            name
            description
            isOpen
        }
    }
    assignmentTypes {
        nodes {
            name
            description
        }
    }
    relationTypes {
        nodes {
            name
            description
            inverseName
        }
    }
    templateFieldSpecifications {
        name
        value
    }
}

query searchIssueTemplates($query: String!, $count: Int!) {
    searchIssueTemplates(query: $query, first: $count, filter: { isDeprecated: { eq: false } }) {
        ...DefaultIssueTemplateInfo
    }
}

query firstIssueTemplates($count: Int!) {
    issueTemplates(first: $count, orderBy: [{ field: NAME }], filter: { isDeprecated: { eq: false } }) {
        nodes {
            ...DefaultIssueTemplateInfo
        }
    }
}

query getIssueTemplate($id: ID!) {
    node(id: $id) {
        ... on IssueTemplate {
            ...DefaultIssueTemplateInfo
        }
    }
}

query getIssueTemplateFields($id: ID!) {
    node(id: $id) {
        ... on IssueTemplate {
            ...IssueTemplateFields
        }
    }
}

mutation createIssueTemplate($input: CreateIssueTemplateInput!) {
    createIssueTemplate(input: $input) {
        issueTemplate {
            ...IssueTemplateFields
        }
    }
}
