fragment DefaultIssueInfo on Issue {
    ...DefaultIssueIconInfo
    id
    title
    trackables {
        nodes {
            ...DefaultTrackableInfo
        }
    }
}

fragment IssueListItemInfo on Issue {
    id
    title
    createdAt
    createdBy {
        ...DefaultUserInfo
    }
    state {
        id
        name
    }
    ...DefaultIssueIconInfo
    issueComments {
        totalCount
    }
    labels {
        nodes {
            ...DefaultLabelInfo
            trackables {
                nodes {
                    id
                    name
                    description
                }
            }
        }
    }
    assignments {
        nodes {
            user {
                ...DefaultUserInfo
            }
        }
    }
    priority {
        ...DefaultIssuePriorityInfo
    }
    template {
        id
        name
        description
    }
    type {
        id
        name
        iconPath
    }
    affects {
        nodes {
            id
        }
    }
}

fragment ParticipatingIssueListItemInfo on Issue {
    ...IssueListItemInfo
    trackables(first: 1) {
        nodes {
            __typename
            id
            name
            description
        }
        totalCount
    }
}

fragment ProjectComponentIssueListItemInfo on Issue {
    ...IssueListItemInfo
    trackables(filter: { isComponentAnd: { versions: { any: { partOfProject: $project } } } }) {
        nodes {
            __typename
            id
            name
            description
        }
        totalCount
    }
}

fragment DefaultIssueIconInfo on Issue {
    incomingRelations {
        totalCount
    }
    outgoingRelations {
        totalCount
    }
    state {
        isOpen
    }
    type {
        iconPath
    }
}

