fragment DefaultViewInfo on View {
    id
    name
    description
    filterByTemplate {
        nodes {
            id
            name
        }
    }
}

fragment ViewGraphInfo on View {
    ...DefaultViewInfo
    relationLayouts {
        nodes {
            relation {
                id
            }
            points {
                x
                y
            }
        }
    }
    relationPartnerLayouts {
        nodes {
            relationPartner {
                id
            }
            pos {
                x
                y
            }
        }
    }
}

